version: '3.8'

services:
  cinema_db:
    image: postgres:16.3
    volumes:
      - ./cinema-service.sql:/docker-entrypoint-db.d/cinema.sql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cinema_db

    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"


networks:
  rabbitmq_go_net:
    driver: bridge