spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:/config/liquibase/changelog.xml
  